# Site settings
title_pt: Embaixada Portuguesa em Singapura
title_en: Portuguese Embassy in Singapore
email: hi@balazar.net
description_en: >
  The official website of the Embassy of Portugal in Singapore.
  This will enable you to have access to the services provided by our Consulates,
  like education, travel and visa information
description_pt: >
  Sítio oficial da Embaixada de Portugal em Singapura.
  Neste “site” encontrará informação relativa a Portugal nomeadamente educação,
  cultura, vistos e eventos, e também, às actividades desenvolvidas pelos nossos Consulados.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.embaixadasingapura.com" # the base hostname & protocol for your site
twitter_username: rpbaltazar
github_username:  rpbaltazar

# Build settings
markdown: kramdown

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']

assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
sass:
  style: compressed
